version: '3'
services:
  srs:
    image: ossrs/srs:3
    ports:
      - 1935:1935
      - 1985:1985
      - 8080:8080
    volumes:
      - ./srs/srs.conf:/usr/local/srs/conf/srs.conf
      - ./srs/srs.log:/usr/local/srs/objs/srs.log
    restart: always
  ffmpeg-bash:
    image: jrottenberg/ffmpeg:4.2-centos
    working_dir: /app
    entrypoint: bash streamer.sh
    volumes:
      - ./ffmpeg/streamer.sh:/app/streamer.sh
      - ./ffmpeg/urls.txt:/app/urls.txt
    depends_on:
      - srs
    restart: always